

spring.application.name=expense-management-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_management
spring.datasource.username=postgres
spring.datasource.password=root
server.port=8081
spring.jpa.hibernate.ddl-auto=create



spring.jpa.show-sql=true


